// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P01_Console;

namespace P01_Console.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210224083927_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("P01_Console.Number", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumberPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhonebookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhonebookId");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("P01_Console.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersonIsFemale")
                        .HasColumnType("bit");

                    b.Property<string>("PersonLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonWebsiteAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("P01_Console.PhoneBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PhonebookPersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhonebookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhonebookPersonId");

                    b.ToTable("PhoneBooks");
                });

            modelBuilder.Entity("P01_Console.Number", b =>
                {
                    b.HasOne("P01_Console.PhoneBook", "NumberPhonebook")
                        .WithMany("PhonebookNumbers")
                        .HasForeignKey("PhonebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumberPhonebook");
                });

            modelBuilder.Entity("P01_Console.PhoneBook", b =>
                {
                    b.HasOne("P01_Console.Person", "PhonebookPerson")
                        .WithMany("PersonPhonebooks")
                        .HasForeignKey("PhonebookPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhonebookPerson");
                });

            modelBuilder.Entity("P01_Console.Person", b =>
                {
                    b.Navigation("PersonPhonebooks");
                });

            modelBuilder.Entity("P01_Console.PhoneBook", b =>
                {
                    b.Navigation("PhonebookNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
